/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'swang' at '7/10/14 12:00 PM' with Gradle 2.0
 *
 * @author swang, @date 7/10/14 12:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
